/*
  Do not edit this file directly. To configure your project and auth, create
  a `.env` file in the root of this project and add the following:

  PROJECT="..."
  SESSION_COOKIE="..."
  
  To get your session secret, log in to https://keystatic.cloud in your browser
  and then inspect the cookies; copy the value of the `keystatic.session`
  cookie into your `.env` file as the value of SESSION_COOKIE.

  Then go to your project config and copy your Project Key into your `.env` as
  the value of PROJECT. It will look something like "team/project".
*/

if (!process.env.PROJECT) {
  throw new Error(
    'You must set the PROJECT environment variable to your Keystatic Cloud Project Key.',
  );
}

if (!process.env.SESSION_COOKIE) {
  throw new Error(
    'You must set the SESSION_COOKIE environment variable to your Keystatic Cloud session cookie.',
  );
}

export const HEADERS = {
  Cookie: `keystatic.session=${process.env.SESSION_COOKIE};`,
  Origin: 'https://keystatic.cloud',
};

const [teamKey, projectKey] = process.env.PROJECT.split('/');

export const KEYSTATIC_CLOUD_BASE_PROJECT_URL = `https://keystatic.cloud/teams/${teamKey}/project/${projectKey}`;
export const KEYSTATIC_CLOUD_UPLOAD_URL = `${KEYSTATIC_CLOUD_BASE_PROJECT_URL}/images/upload`;

export const UPLOAD_FROM_DIR = './images';
export const RESULTS_PATH = './results.json';
